### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by OlivierSohn**

### CODE REVIEW

**Comment by sgraf812** [comment]
Thanks!

**Comment by OlivierSohn** [comment]
You're welcome ! I was looking at your project as I try to learn about GHC strictness analysis :)

**Comment by sgraf812** [comment]
Yeah, I'm planning to release this soon (tm), but want to write an accompanying blog post that implements just that for documentation purposes. Procrastination, I guess.

**Comment by OlivierSohn** [comment]
Thanks for the link to the doc! Out of curiosity, is it used or do you know if it is planned to be used in GHC?

**Comment by sgraf812** [comment]
I'd love to use it in GHC, but currently there are some blockers:

1. Performance is uncertain. The benchmark suite suggests this is a little slower than manual AST traversals. I think this would at least be a concern. On the bright side, we have more knobs to tune analysis performance.
2. The dependency footprint is probably to huge to be included into GHC right now.

Time will tell if a variant of this will eventually find its way into GHC, but I think a number of hobby to semi-professional middle-ends like that of Idris could use this.

**Pull request merged**
